package pzopt;

import java.io.File;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL13;
import org.lwjgl.opengl.GL30;
import zombie.characters.IsoPlayer;
import zombie.core.opengl.Shader;
import zombie.core.opengl.ShaderProgram;
import zombie.core.rendering.RenderTarget;
import zombie.core.textures.Texture;
import zombie.core.textures.TextureFBO;
import zombie.iso.Vector2;

/**
 * The vision cone's edge blur, split in two passes ({@code visBlurReduce}, 2026-09-24, the E-core pass).
 *
 * <p>Stock {@code visibilityBlur} draws one full-screen quad over the world buffer, and every fragment sums 25 texels of
 * the half-resolution vision texture: at the widest zoom the world buffer is 2.5 x the screen per axis, ~13 million
 * fragments and ~340 million texture reads a frame, the biggest pass after the chunk composite on the flip's 890M. The
 * sum depends only on the vision-texture texel a fragment maps to ({@code pixel}, an integer), so here it is computed once
 * per texel ({@code pzopt_visBlurReduce}: the stock loop verbatim, into a float texture the size of the vision texture)
 * and the screen pass ({@code pzopt_visibilityBlur}: the stock shader with the loop replaced by one texelFetch) reads it.
 * Same arithmetic, same result. Both shaders are generated by scripts/build.sh from the installed game's shader. One
 * player only (split screen maps fragments with an origin offset; it keeps the stock pass).
 */
public final class VisBlur {
   public static final boolean ON = Config.VIS_BLUR_REDUCE && Overrides.enabled();
   private static Shader reduceShader, screenShader;
   private static Texture reduceTex;
   private static TextureFBO reduceFbo;
   private static boolean broken;
   private static final Vector2 v = new Vector2();
   public static long passes;

   private VisBlur() {
   }

   /**
    * Render thread, in VisibilityPolygon2's screen pass before its shader starts: runs the reduce pass over
    * {@code blurTex} and returns the screen shader to use instead of the stock one, or null for the stock pass. Leaves
    * the viewport to the caller (it sets its own right after) and blending / depth testing enabled as it found them.
    */
   public static Shader reduce(Texture blurTex) {
      if (!ON || broken || IsoPlayer.numPlayers > 1 || blurTex == null) {
         return null;
      }
      try {
         if (reduceShader == null) {
            if (!new File("media/shaders/pzopt_visBlurReduce.frag").isFile() || !new File("media/shaders/pzopt_visibilityBlur.frag").isFile()) {
               broken = true;
               Log.warn("visBlurReduce: shaders not installed (media/shaders/pzopt_visBlurReduce.*); stock blur");
               return null;
            }
            reduceShader = new Shader("pzopt_visBlurReduce");
            screenShader = new Shader("pzopt_visibilityBlur");
            if (!reduceShader.isCompiled() || !screenShader.isCompiled()) {
               broken = true;
               Log.warn("visBlurReduce: shaders did not compile (reduce " + reduceShader.isCompiled() + ", screen " + screenShader.isCompiled() + "); stock blur");
               return null;
            }
            Log.info("visBlurReduce: vision-cone blur summed once per vision texel");
         }
         int w = blurTex.getWidth();
         int h = blurTex.getHeight();
         if (reduceTex == null || reduceTex.getWidth() != w || reduceTex.getHeight() != h) {
            if (reduceTex != null) {
               reduceTex.destroy();
            }
            reduceTex = new Texture(w, h, 16, 6403, 33326); // GL_RED / GL_R32F: the raw sum, as the stock shader keeps it
            reduceTex.setNameOnly("pzoptVisBlurSum");
            if (reduceFbo == null) {
               reduceFbo = new TextureFBO(reduceTex, false);
            } else {
               reduceFbo.startDrawing(false, false);
               reduceFbo.attach(reduceTex, 36064);
               reduceFbo.endDrawing();
            }
            // TextureFBO allocates its colour texture as RGBA8 whatever the Texture asked for, which would clamp the sum
            // (0..25) to 1: give it single-channel float storage (the attachment follows the texture object)
            GL13.glActiveTexture(GL13.GL_TEXTURE0);
            GL11.glBindTexture(GL11.GL_TEXTURE_2D, reduceTex.getID());
            GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL30.GL_R32F, reduceTex.getWidthHW(), reduceTex.getHeightHW(), 0, GL11.GL_RED, GL11.GL_FLOAT, (java.nio.FloatBuffer) null);
            GL11.glBindTexture(GL11.GL_TEXTURE_2D, 0);
            Texture.lastTextureID = 0;
         }
         GL11.glDisable(GL11.GL_BLEND);
         GL11.glDisable(GL11.GL_DEPTH_TEST);
         GL11.glViewport(0, 0, w, h);
         reduceFbo.startDrawing(false, false);
         reduceShader.Start();
         ShaderProgram p = reduceShader.getProgram();
         p.setValue("tex", blurTex, 0);
         v.set(w, h);
         p.setValue("texSize", v);
         v.set(blurTex.getWidthHW(), blurTex.getHeightHW());
         p.setValue("TextureSize", v);
         RenderTarget.DrawFullScreenQuad();
         reduceShader.End();
         reduceFbo.endDrawing();
         GL11.glEnable(GL11.GL_BLEND);
         GL11.glEnable(GL11.GL_DEPTH_TEST);
         passes++;
         return screenShader;
      } catch (Throwable t) {
         broken = true;
         Log.warn("visBlurReduce: " + t + "; stock blur from now on");
         GL11.glEnable(GL11.GL_BLEND);
         GL11.glEnable(GL11.GL_DEPTH_TEST);
         return null;
      }
   }

   /** The per-texel sums of the last reduce pass (sampler "reduced" of the screen shader). */
   public static Texture sums() {
      return reduceTex;
   }
}
