apiVersion: 1
datasources:
  - name: pzopt
    uid: pzopt-pg
    type: grafana-postgresql-datasource
    url: localhost:5432
    user: grafana
    isDefault: true
    jsonData:
      database: pzopt
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 10
    secureJsonData:
      password: grafana
